version: '3.9'

services:
  src:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USE_TLS=1
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=DelacruaRssReader@gmail.com
      - EMAIL_HOST_PASS=qqyskdonikrhvgmi
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
