on:
  pull_request:
    types: [opened, edited]

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

name: "Mark Final Task"
jobs:
  label_regex:
    runs-on: ubuntu-latest
    name: Add label
    steps:
      - name: "Assign label to Final Task"
        uses: Bhacaz/label-regex@v1
        with:
          field: title
          regex: '(?<final_task>(F|f)(I|i)(N|n)(A|a)(L|l)[ -]*(T|t)(A|a)(S|s)(K|k)).*'
          lowercase: true
          token: "${{ secrets.GITHUB_TOKEN }}"
